### ISSUE TITLE
render events on scheduler when its on-schedule in CR report Edit.

### ISSUE THREAD

**Issue by ijunaid8989** [evercam/evercam-admin3#25]

**Comment by marcoherbst** [comment]
@ijunaid8989 could you explain this a bit better ... some context.

**Comment by ijunaid8989** [comment]
Follow up:

When you try to Edit cloud recordings on /cloud_recordings report.
on-schedule cloud recordings get opened in POP UP but scheduler doesn't get filled up with on scheduled events.

**Comment by ijunaid8989** [comment]
We are using this https://github.com/CroudTech/vue-fullcalendar

which in the back also using jquery. 
Right now the issue is: It's not letting me render custom events and then also remove them, I am switching to a pure Jquery solution for this else, I don't see anything working with this Vue Implementation of Full Calendar.

**Comment by ijunaid8989** [comment]
its done.

I have added fullCalendar 4.0 ES6 based they are not supporting jquery anymore now.
